// Generated by LiveScript 1.5.0
(function(){
  var Generator, textarea, copy;
  Generator = require('./shesha').Generator;
  textarea = document.querySelector('textarea');
  textarea.onkeyup = function(){
    var gen, e;
    gen = Generator();
    try {
      gen.readGenerator(textarea.value);
      return gen.makeWidget(document.querySelector('.shesha-widget'));
    } catch (e$) {
      e = e$;
      return console.log(e);
    }
  };
  textarea.onkeyup();
  copy = document.querySelector('#copy');
  copy.onclick = function(){
    var dummy;
    dummy = document.querySelector('#dummy');
    dummy.value = '<script type="text/plain" class="shesha-widget">\n' + textarea.value + '\n</script>\n';
    dummy.value += '<script async src="https://rawgit.com/polm/shesha/master/embed.js"></script>';
    dummy.select();
    return document.execCommand('Copy');
  };
}).call(this);
