// Generated by LiveScript 1.5.0
(function(){
  var Generator, CodeMirror, Split, split, textarea, codemirror, updateGenerator, copy;
  Generator = require('./shesha').Generator;
  require('codemirror/addon/mode/simple');
  CodeMirror = require('codemirror');
  Split = require('split.js');
  CodeMirror.defineSimpleMode('shesha', {
    start: [
      {
        regex: /\#.*/,
        token: 'comment'
      }, {
        regex: /(deck)(\s+)(.*)/,
        token: ['keyword', null, 'variable-2'],
        next: 'block',
        sol: true
      }, {
        regex: /(die)(\s+)(.*)/,
        token: ['keyword', null, 'variable-2'],
        next: 'block',
        sol: true
      }, {
        regex: /generator/,
        token: 'keyword',
        next: 'generator',
        sol: true
      }
    ],
    block: [{
      regex: /\#.*/,
      token: 'comment'
    }],
    generator: [
      {
        regex: /\#.*/,
        token: 'comment'
      }, {
        regex: /([^ ]+)\s/,
        sol: true,
        token: 'atom'
      }, {
        regex: /\[/,
        push: 'bracket'
      }
    ],
    bracket: [
      {
        regex: /\[/,
        push: 'bracket'
      }, {
        regex: /[^\]]+/,
        token: 'string'
      }, {
        regex: /\]/,
        pop: true
      }
    ],
    meta: {
      lineComment: '#',
      blankLine: function(it){
        return it.state = 'start';
      }
    }
  });
  split = Split(['#editor', '#field'], {
    sizes: [60, 40],
    gutterSize: 10,
    minSize: [100, 520],
    elementStyle: function(dim, size, gutsize){
      return {
        'flex-basis': "calc(" + size + "% - " + gutsize + "px"
      };
    },
    gutterStyle: function(dim, gutsize){
      return {
        'flex-basis': gutsize + 'px',
        borderRight: '10px groove #ddd'
      };
    }
  });
  textarea = document.querySelector('textarea');
  codemirror = CodeMirror.fromTextArea(textarea, {
    lineWrapping: true,
    lineNumbers: false,
    mode: 'shesha',
    theme: 'paraiso-dark'
  });
  updateGenerator = function(){
    var gen, e;
    gen = Generator();
    try {
      gen.readGenerator(codemirror.getValue());
      return gen.makeWidget(document.querySelector('.shesha-widget'));
    } catch (e$) {
      e = e$;
      return console.log(e);
    }
  };
  codemirror.on('change', updateGenerator);
  updateGenerator();
  copy = document.querySelector('#copy');
  copy.onclick = function(){
    var dummy;
    dummy = document.querySelector('#dummy');
    dummy.value = '<script type="text/plain" class="shesha-widget">\n' + codemirror.getValue() + '\n</script>\n';
    dummy.value += '<script async src="https://rawgit.com/polm/shesha/master/embed.js"></script>';
    dummy.select();
    return document.execCommand('Copy');
  };
}).call(this);
