// Generated by LiveScript 1.5.0
(function(){
  var Generator, i$, ref$, len$, el, gen, widgetContainer;
  Generator = require('./shesha').Generator;
  for (i$ = 0, len$ = (ref$ = document.querySelectorAll('.shesha-widget')).length; i$ < len$; ++i$) {
    el = ref$[i$];
    el.classList.remove('shesha-widget');
    gen = new Generator();
    widgetContainer = document.createElement('div');
    widgetContainer.style.opacity = 0;
    widgetContainer.style.maxWidth = '800px';
    el.parentNode.insertBefore(widgetContainer, el.nextSibling);
    gen.readGenerator(el.textContent);
    gen.makeWidget(widgetContainer);
  }
}).call(this);
