// Generated by LiveScript 1.5.0
(function(){
  var Shesha, fs, args, mode, gen, readSourceData, arg, key, ref$, val;
  Shesha = require('./shesha');
  fs = require('fs');
  args = process.argv.slice(2);
  mode = 'template';
  gen = new Shesha.Generator();
  readSourceData = function(){
    var fname;
    fname = args.shift();
    return JSON.parse(fs.readFileSync(fname, 'utf-8'));
  };
  while (args.length > 0) {
    arg = args.shift();
    switch (arg) {
    case '-c':
      for (key in ref$ = readSourceData()) {
        val = ref$[key];
        gen.addDeck(key, val);
      }
      break;
    case '-d':
      for (key in ref$ = readSourceData()) {
        val = ref$[key];
        gen.addDie(key, val);
      }
      break;
    case '-t':
      gen.readGenerator(fs.readFileSync(args.shift(), 'utf-8'));
      break;
    default:
      console.log(gen.render(arg));
    }
  }
}).call(this);
